CREATE TABLE IF NOT EXISTS USER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email TEXT UNIQUE,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS ROLE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES ROLE(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    manager_id INTEGER,
    created_at DATETIME,
    updated_at DATETIME,

    FOREIGN KEY(manager_id)
    REFERENCES EMPLOYEE(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS GOAL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT,
    start_date DATE,
    end_date DATE
);

CREATE TABLE IF NOT EXISTS DEPARTMENT_GOALS (
    department_id INTEGER NOT NULL,
    goal_id INTEGER NOT NULL,
    PRIMARY KEY(department_id, goal_id),
    FOREIGN KEY(department_id) REFERENCES DEPARTMENT(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(goal_id) REFERENCES GOAL(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dni TEXT NOT NULL UNIQUE,
    birthdate DATE,
    phone_number TEXT,
    email TEXT,
    address TEXT,
    hire_date DATE,
    salary INTEGER,
    department_id INTEGER,
    position TEXT,
    status TEXT,
    user_id INTEGER,
    FOREIGN KEY(department_id) REFERENCES DEPARTMENT(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS BENEFIT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    amount INTEGER
);

CREATE TABLE IF NOT EXISTS DEDUCTION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    amount INTEGER
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_BENEFITS (
    employee_id INTEGER NOT NULL,
    benefit_id INTEGER NOT NULL,
    PRIMARY KEY(employee_id, benefit_id),
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE,
    FOREIGN KEY(benefit_id) REFERENCES BENEFIT(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_DEDUCTIONS (
    employee_id INTEGER NOT NULL,
    deduction_id INTEGER NOT NULL,
    PRIMARY KEY(employee_id, deduction_id),
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE,
    FOREIGN KEY(deduction_id) REFERENCES DEDUCTION(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SALARY (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER NOT NULL,
    old_salary INTEGER,
    new_salary INTEGER,
    change_date DATE,
    reason TEXT,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PAYROLL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER NOT NULL,
    month TEXT,
    year INTEGER,
    base INTEGER,
    gross INTEGER,
    net INTEGER,
    payment_date DATE,
    status TEXT,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RECEIPT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payroll_id INTEGER NOT NULL,
    concept TEXT,
    amount INTEGER,
    type TEXT,
    FOREIGN KEY(payroll_id) REFERENCES PAYROLL(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REPORT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    receipt_id INTEGER NOT NULL,
    month TEXT,
    year INTEGER,
    FOREIGN KEY(receipt_id) REFERENCES RECEIPT(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ABSENCE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER NOT NULL,
    start_date DATE,
    end_date DATE,
    type TEXT,
    reason TEXT,
    status TEXT,
    created_at DATETIME,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message TEXT,
    sent_date DATETIME,
    read BOOLEAN
);

CREATE TABLE IF NOT EXISTS ABSENCE_NOTIFICATION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    absence_id INTEGER NOT NULL,
    notification_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    FOREIGN KEY(absence_id) REFERENCES ABSENCE(id) ON DELETE CASCADE,
    FOREIGN KEY(notification_id) REFERENCES NOTIFICATION(id) ON DELETE CASCADE,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REQUEST (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER NOT NULL,
    days_requested INTEGER,
    start_date DATE,
    end_date DATE,
    reason TEXT,
    status TEXT,
    created_at DATETIME,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LEAVE_NOTIFICATION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    request_id INTEGER NOT NULL,
    notification_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    FOREIGN KEY(request_id) REFERENCES REQUEST(id) ON DELETE CASCADE,
    FOREIGN KEY(notification_id) REFERENCES NOTIFICATION(id) ON DELETE CASCADE,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BALANCE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER NOT NULL UNIQUE,
    total_days INTEGER,
    used_days INTEGER,
    days_remaining INTEGER,
    updated_at DATETIME,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);
