

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    manager_id INTEGER
);

CREATE TABLE IF NOT EXISTS GOAL (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTMENT_GOALS(
    department_id INTEGER NOT NULL,
    goal_id INTEGER NOT NULL,
    PRIMARY KEY(department_id,goal_id),
    FOREIGN KEY (department_id) REFERENCES DEPARTMENT(id) ON DELETE CASCADE,
    FOREIGN KEY (goal_id) REFERENCES GOAL(id) ON DELETE CASCADE
)