CREATE TABLE IF NOT EXISTS DEPARTMENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    manager_id INTEGER,
    created_at DATE
);

CREATE TABLE IF NOT EXISTS PROJECT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT,
    department_id INTEGER NOT NULL,
    start_date DATE,
    end_date DATE,
    FOREIGN KEY (department_id) REFERENCES DEPARTMENT(id) ON DELETE CASCADE
);