CREATE TABLE IF NOT EXISTS EMPLOYEE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dni TEXT NOT NULL UNIQUE,
    birthdate DATE,
    phone_number TEXT,
    email TEXT,
    address TEXT,
    hire_date DATE,
    salary INTEGER,
    department_id INTEGER,
    position TEXT,
    status TEXT,
    user_id INTEGER,
    FOREIGN KEY(department_id) REFERENCES DEPARTMENT(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS BENEFIT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    amount INTEGER
);

CREATE TABLE IF NOT EXISTS DEDUCTION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    amount INTEGER
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_BENEFITS (
    employee_id INTEGER NOT NULL,
    benefit_id INTEGER NOT NULL,
    PRIMARY KEY(employee_id, benefit_id),
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE,
    FOREIGN KEY(benefit_id) REFERENCES BENEFIT(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_DEDUCTIONS (
    employee_id INTEGER NOT NULL,
    deduction_id INTEGER NOT NULL,
    PRIMARY KEY(employee_id, deduction_id),
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE,
    FOREIGN KEY(deduction_id) REFERENCES DEDUCTION(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SALARY (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id INTEGER NOT NULL,
    old_salary INTEGER,
    new_salary INTEGER,
    change_date DATE,
    reason TEXT,
    FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

DROP TABLE DEPARTMENT;
DROP TABLE PROJECT;

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    manager_id INTEGER,
    created_at DATE,
    FOREIGN KEY (manager_id) REFERENCES EMPLOYEE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PROJECT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT,
    department_id INTEGER NOT NULL,
    start_date TEXT,
    end_date TEXT,
    FOREIGN KEY (department_id) REFERENCES DEPARTMENT(id) ON DELETE CASCADE
);